cabal-version:      3.0
--   http://haskell.org/cabal/users-guide/
name:               Mat

version:            0.1.0.0

synopsis:           Type theory based math editor inteded for univalent foundations.

-- description:

author:             Malte Kildelund Rosenkilde

common warnings
    ghc-options: -Wall

executable Mat
    import:           warnings

    main-is:          Main.hs

    other-modules:
        TypeTheory

    build-depends:
        base ^>=4.20.2.0
      -- , monomer ^>=1.6.0.1

    hs-source-dirs:   src

    default-language: Haskell2010
